cookie:
  expiry_days: 1
  key: some_signature_key
  name: some_cookie_name
credentials:
  usernames:
    jsmith:
      email: u1@testmail.com
      failed_login_attempts: 0
      first_name: John
      last_name: Smith
      logged_in: false
      password: abc
      roles:
      - Administrator
pre-authorized:
  emails: null
pre-authorized2:
  emails:
  - u1@testmail.com
